# code: language=ansible

- name: NAS Setup
  hosts: nas.home.derham.me
  become: true
  vars:
    base_dir: /srv

  tasks:
    - name: Ensure the base directory exists
      ansible.builtin.file:
        path: /etc/terminfo/a/
        state: directory
        mode: "0755"

    - name: Copy terminfo
      ansible.builtin.copy:
        src: files/alacritty.terminfo
        dest: /etc/terminfo/a/alacritty
        owner: root
        group: root
        mode: "0644"

    - name: Mount the root partition
      ansible.posix.mount:
        src: UUID=4a1da395-ad7a-4c1d-8c3c-ea724fb7ee7d
        path: /
        fstype: ext4
        state: mounted

    - name: Mount the footage disk
      ansible.posix.mount:
        src: UUID=36ce0e8c-f7c5-476f-a706-d8ded1c467cf
        path: /mnt/footage
        fstype: ext4
        state: mounted

    # TODO: Add backup disk
    # - name: Mount the backup disk
    #   ansible.posix.mount:
    #     src: UUID=
    #     path: /mnt/backup
    #     fstype: ext4
    #     state: mounted

    - name: Bootstrap the hosts to trust the CA
      ansible.builtin.include_role:
        name: maxhoesel.smallstep.step_bootstrap_host
      vars:
        step_cli_version: "0.24.4"
        step_bootstrap_ca_url: https://ca.home.derham.me
        step_bootstrap_fingerprint: "e0d6b8d064a2bb9adbaf327363a36f2f5233de3aa518fb9c0d9f83182e0b5a1c"

    - name: Install Podman
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - podman
        - podman-docker
      tags:
        - podman

    - name: Enable Podman socket
      ansible.builtin.systemd:
        name: podman.socket
        enabled: true
        state: started
      tags:
        - podman

    - name: Install Caddy
      ansible.builtin.include_role:
        name: caddy
        apply:
          tags:
            - caddy
      tags:
        - caddy

    - name: Install Mosquitto
      ansible.builtin.include_role:
        name: mosquitto
        apply:
          tags:
            - mosquitto
      tags:
        - mosquitto

    - name: Install Home Assistant
      ansible.builtin.include_role:
        name: homeassistant
        apply:
          tags:
            - homeassistant
      tags:
        - homeassistant

    - name: Install Frigate
      ansible.builtin.include_role:
        name: frigate
        apply:
          tags:
            - frigate
      tags:
        - frigate

    - name: Install Unifi
      ansible.builtin.include_role:
        name: unifi
        apply:
          tags:
            - unifi
      tags:
        - unifi

    - name: Install Homepage
      ansible.builtin.include_role:
        name: homepage
        apply:
          tags:
            - homepage
      tags:
        - homepage

    - name: Install Transmission
      ansible.builtin.include_role:
        name: transmission
        apply:
          tags:
            - transmission
      tags:
        - transmission
