# code: language=ansible

- name: Create app
  ansible.builtin.import_tasks: tasks/application.yaml
  vars:
    name: mosquitto
    uid: 1883
    dirs:
      - config

- name: Mosquitto config file
  ansible.builtin.copy:
    src: mosquitto.conf
    dest: "{{ base_dir }}/mosquitto/config/mosquitto.conf"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0744"

- name: Create Podman network
  containers.podman.podman_network:
    name: mosquitto

- name: Start mosquitto
  containers.podman.podman_container:
    name: mosquitto
    image: docker.io/eclipse-mosquitto:2.0
    state: started
    restart_policy: "unless-stopped"
    network:
      - mosquitto
    volumes:
      - "{{ app_dir.path }}:/mosquitto"
    ports:
      - 1883
      - 9001
    user: "{{ user.uid }}"
