# code: language=ansible

- name: Create app
  ansible.builtin.import_tasks: tasks/application.yaml
  vars:
    name: homeassistant

- name: Create Podman network
  containers.podman.podman_network:
    name: caddy
  register: caddy_network

- name: Template Homeassistant config
  ansible.builtin.template:
    src: configuration.yaml.j2
    dest: "{{ app_dir.path }}/configuration.yaml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0744"

- name: Start Homeassistant
  containers.podman.podman_container:
    name: homeassistant
    image: lscr.io/linuxserver/homeassistant:2023.8.3
    state: started
    restart_policy: "unless-stopped"
    network:
      - mosquitto
      - caddy
    env:
      PUID: "{{ user.uid }}"
      PGID: "{{ user.group }}"
      TZ: Europe/London
      REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
    labels:
      caddy: homeassistant.home.derham.me
      caddy.reverse_proxy: "{% raw %}{{upstreams 8123}}{% endraw %}"
      homepage.group: Automation
      homepage.name: Home Assistant
      homepage.icon: home-assistant.png
      homepage.href: http://homeassistant.home.derham.me/
      homepage.description: Automation dashboard
    volumes:
      - "{{ app_dir.path }}:/config"
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - /mnt/footage:/mnt/footage:ro
    ports:
      - 8123
    # TODO: Add USB devices for Z-Wave and Zigbee
    # device:
    #   - /dev/ttyACM0:/dev/ttyACM0

- name: Download HACS
  ansible.builtin.get_url:
    url: https://get.hacs.xyz
    dest: /tmp/hacs-installer.sh
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0744"
    force: true
  register: hacs_download

- name: Install wget for HACS script
  ansible.builtin.package:
    name: wget
    state: present

- name: Install unzip for HACS script
  ansible.builtin.package:
    name: unzip
    state: present

- name: Install HACS
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.shell: /tmp/hacs-installer.sh
  args:
    chdir: "{{ app_dir.path }}"
  when: hacs_download.changed
